421final/Controllers/ReportsPageController.cs
using _421final.Data;
using _421final.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Net;
using System.Text.Json;


namespace _421final.Controllers
{
    public class ReportsPageController : Controller
    {
        private ApplicationDbContext _context;

        public ReportsPageController(ApplicationDbContext context)
        {
            _context = context;
        }


        [Authorize(Roles = SD.User + "," + SD.Admin)]
        public async Task<IActionResult> Index()
        {
            ReportsPage vm = new ReportsPage();
            vm.playerList = await _context.PlayerRoot.ToListAsync();
            vm.teamList = await _context.TeamRoot.ToListAsync();
            vm.NoChampionList = NonChampionshipList(vm.teamList);
            vm.ChampionList = ChampionshipList(vm.teamList);
            vm.WeightList = WeightList(vm.playerList);
            vm.HeightList = HeightList(vm.playerList);


            vm.ChampionList.OrderBy(x => x.Championships).ToList();
            return View(vm);

        }

        private static List<TeamRoot> ChampionshipList(List<TeamRoot> teamList)
        {
            List<TeamRoot> championshipList = new List<TeamRoot>();

            
        
            foreach(var team in teamList)
            {
                if(team.Championships >= 1)
                {
                    championshipList.Add(team);
                }
            }

            championshipList.OrderBy(x => x.Championships).ToList();

            return championshipList; 
        }

        private static List<TeamRoot> NonChampionshipList(List<TeamRoot> teamList)
        {
            List<TeamRoot> championshipList = new List<TeamRoot>();


            foreach (var team in teamList)
            {
                if (team.Championships <= 0)
                {
                    championshipList.Add(team);
                }
            }

            championshipList.OrderBy(x => x.Championships).ToList();

            return championshipList;
        }

        private static List<PlayerRoot> WeightList(List<PlayerRoot> playerList)
        {
            List<PlayerRoot> newPlayerList = new List<PlayerRoot>();


            foreach (var player in playerList)
            {
                if (player.WeightPounds < 200)
                {
                    newPlayerList.Add(player);
                }
            }

            newPlayerList.OrderBy(x => x.WeightPounds).ToList();

            return newPlayerList;
        }


        private static List<PlayerRoot> HeightList(List<PlayerRoot> playerList)
        {
            List<PlayerRoot> newPlayerList = new List<PlayerRoot>();


            foreach (var player in playerList)
            {
                if (player.HeightFeet >= 7)
                {
                    newPlayerList.Add(player);
                }
            }

            newPlayerList.OrderBy(x => x.HeightFeet).ThenBy(x=> x.HeightInches).ToList();

            return newPlayerList;
        }




    }
}

421final/Controllers/TeamRootsController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using _421final.Data;
using _421final.Models;
using System.Net;
using System.Text.Json;
using Microsoft.AspNetCore.Authorization;

namespace _421final.Views
{
    public class TeamRootsController : Controller
    {
        private ApplicationDbContext _context;

        public TeamRootsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: TeamRoots
        public async Task<IActionResult> Index()
        {
                return View(await _context.TeamRoot.ToListAsync());
        }


        // GET: TeamRoots/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var teamRoot = await _context.TeamRoot
                .FirstOrDefaultAsync(m => m.Id == id);
            if (teamRoot == null)
            {
                return NotFound();
            }
            return View(teamRoot);
        }

        [Authorize(Roles = SD.Admin)]
        // GET: TeamRoots/Create
        public async Task<IActionResult> Create()
        {
            //retrieves all 30 teams and stores in database
            /*WebRequest request = WebRequest.Create("https://www.balldontlie.io/api/v1/teams");
            WebResponse response = request.GetResponse();
            // Display the status.
            Console.WriteLine(((HttpWebResponse)response).StatusDescription);

            // Get the stream containing content returned by the server.
            // The using block ensures the stream is automatically closed.
            using (Stream dataStream = response.GetResponseStream())
            {
                using (var transaction = _context.Database.BeginTransaction())
                {
                    // Open the stream using a StreamReader for easy access.
                    StreamReader reader = new StreamReader(dataStream);
                    // Read the content.
                    string jsonString = reader.ReadToEnd();
                    AllTeamsRoot? teamData = JsonSerializer.Deserialize<AllTeamsRoot>(jsonString);
                    //save to DB
                    foreach (var i in (IEnumerable<TeamRoot>)teamData.Data)
                    {
                        TeamRoot newTeam = new TeamRoot();
                        newTeam.Id = i.Id;
                        newTeam.Abbreviation = i.Abbreviation;
                        newTeam.City = i.City;
                        newTeam.Conference = i.Conference;
                        newTeam.Division = i.Division;
                        newTeam.FullName = i.FullName;
                        newTeam.Name = i.Name;
                        _context.Add(newTeam);
                    }
                    _context.Database.ExecuteSqlRaw(@"SET IDENTITY_INSERT [dbo].[TeamRoot] ON");
                    await _context.SaveChangesAsync();
                    _context.Database.ExecuteSqlRaw(@"SET IDENTITY_INSERT [dbo].[TeamRoot] OFF");
                    transaction.Commit();
                }

            }*/
            
            return View();
        }

        // POST: TeamRoots/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Abbreviation,City,Conference,Division,FullName,Name,Championships")] TeamRoot teamRoot)
        {
            if (ModelState.IsValid)
            {
                _context.Add(teamRoot);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(teamRoot);
        }

        [Authorize(Roles = SD.Admin)]
        // GET: TeamRoots/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var teamRoot = await _context.TeamRoot.FindAsync(id);
            if (teamRoot == null)
            {
                return NotFound();
            }
            return View(teamRoot);
        }

        // POST: TeamRoots/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Abbreviation,City,Conference,Division,FullName,Name,Championships")] TeamRoot teamRoot)
        {
            if (id != teamRoot.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(teamRoot);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TeamRootExists(teamRoot.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(teamRoot);
        }

        [Authorize(Roles = SD.Admin)]
        // GET: TeamRoots/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var teamRoot = await _context.TeamRoot
                .FirstOrDefaultAsync(m => m.Id == id);
            if (teamRoot == null)
            {
                return NotFound();
            }

            return View(teamRoot);
        }

        // POST: TeamRoots/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var teamRoot = await _context.TeamRoot.FindAsync(id);
            _context.TeamRoot.Remove(teamRoot);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TeamRootExists(int id)
        {
            return _context.TeamRoot.Any(e => e.Id == id);
        }
    }
}

421final/Controllers/UserRolesController.cs
using _421final.Data;
using _421final.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Net;
using System.Text.Json;

namespace _421final.Views
{
     public class UserRolesController : Controller
    {
        private readonly UserManager<IdentityUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;

        public UserRolesController(UserManager<IdentityUser> userManager, RoleManager<IdentityRole> roleManager)
        {
            _roleManager = roleManager;
            _userManager = userManager;
        }

        [Authorize(Roles = SD.Admin)]
        public async Task<IActionResult> Index()
        {
            var users = await _userManager.Users.ToListAsync();
            var userRolesViewModel = new List<UserRolesVM>();
            foreach (IdentityUser user in users)
            {
                var thisViewModel = new UserRolesVM();
                thisViewModel.UserId = user.Id;
                thisViewModel.Email = user.Email;
                thisViewModel.Roles = await GetUserRoles(user);
                userRolesViewModel.Add(thisViewModel);
            }
            return View(userRolesViewModel);
        }
        private async Task<List<string>> GetUserRoles(IdentityUser user)
        {
            return new List<string>(await _userManager.GetRolesAsync(user));
        }

        [Authorize(Roles = SD.Admin)]
        public async Task<IActionResult> Manage(string userId)
        {
            ViewBag.userId = userId;
            var user = await _userManager.FindByIdAsync(userId);
            if (user == null)
            {
                ViewBag.ErrorMessage = $"User with Id = {userId} cannot be found";
                return View("NotFound");
            }
            ViewBag.UserName = user.UserName;
            var model = new List<ManageUserRolesVM>();
            foreach (var role in _roleManager.Roles)
            {
                var userRolesViewModel = new ManageUserRolesVM
                {
                    RoleId = role.Id,
                    RoleName = role.Name
                };
                if (await _userManager.IsInRoleAsync(user, role.Name))
                {
                    userRolesViewModel.Selected = true;
                }
                else
                {
                    userRolesViewModel.Selected = false;
                }
                model.Add(userRolesViewModel);
            }
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Manage(List<ManageUserRolesVM> model, string userId)
        {
            var user = await _userManager.FindByIdAsync(userId);
            if (user == null)
            {
                return View();
            }
            var roles = await _userManager.GetRolesAsync(user);
            var result = await _userManager.RemoveFromRolesAsync(user, roles);
            if (!result.Succeeded)
            {
                ModelState.AddModelError("", "Cannot remove user existing roles");
                return View(model);
            }
            result = await _userManager.AddToRolesAsync(user, model.Where(x => x.Selected).Select(y => y.RoleName));
            if (!result.Succeeded)
            {
                ModelState.AddModelError("", "Cannot add selected roles to user");
                return View(model);
            }
            return RedirectToAction("Index");
        }
    }
}

421final/Views/Shared/_ComparisonLayout.cshtml
@using _421final.Data
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">

<title>BallDon'tLie</title>

<!-- Fav Icon -->
<link rel="icon" href="/assets/images/nba-logo-transparent.ico" type="image/x-icon">

<!-- Google Fonts -->
<link href="https://fonts.googleapis.com/css2?family=DM+Sans:ital,wght@0,400;0,500;0,700;1,400;1,500;1,700&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css2?family=Merriweather+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;0,800;1,300;1,400;1,500;1,600;1,700;1,800&display=swap" rel="stylesheet">

<!-- Stylesheets -->
<link href="/assets/css/font-awesome-all.css" rel="stylesheet">
<link href="/assets/css/flaticon.css" rel="stylesheet">
<link href="/assets/css/owl.css" rel="stylesheet">
<link href="/assets/css/bootstrap.css" rel="stylesheet">
<link href="/assets/css/jquery.fancybox.min.css" rel="stylesheet">
<link href="/assets/css/animate.css" rel="stylesheet">
<link href="/assets/css/nice-select.css" rel="stylesheet">
<link href="/assets/css/color.css" rel="stylesheet">
<link href="/assets/css/style.css" rel="stylesheet">
<link href="/assets/css/responsive.css" rel="stylesheet">
<link href="/css/site.css" rel="stylesheet">
<!-- jequery plugins -->
<script src="/assets/js/jquery.js"></script>
<script src="/assets/js/popper.min.js"></script>
<script src="/assets/js/bootstrap.min.js"></script>
<script src="/assets/js/owl.js"></script>
<script src="/assets/js/wow.js"></script>
<script src="/assets/js/validation.js"></script>
<script src="/assets/js/jquery.fancybox.js"></script>
<script src="/assets/js/appear.js"></script>
<script src="/assets/js/scrollbar.js"></script>
<script src="/assets/js/jquery.nice-select.min.js"></script>
<script src="/assets/js/nav-tool.js"></script>
<!-- main-js -->
<script src="/assets/js/script.js"></script>
<link rel="stylesheet" href="https://cdn.datatables.net/1.11.4/css/jquery.dataTables.min.css" integrity="sha384-yT2pwyD9a3Oee/HtjWTccnRmchDWH2EDHjzH7gwf8yAK0RilKFL164FCHX9fzlxh" crossorigin="anonymous">
<script src="https://cdn.datatables.net/1.11.4/js/jquery.dataTables.js" integrity="sha384-J1VTqRX3eTNk2nvwiGSqxuZEoboOJHEARFiWWeRcyH+cTelYBIQPq9iNWeCqQV2S" crossorigin="anonymous"></script>

<style>
    input[type=text] {
      border: none;
      border-bottom: 2px solid black;
    }
    input[type=number] {
      border: none;
      border-bottom: 2px solid black;
    }
    input[type=button], input[type=submit], input[type=reset] {
      background-color: black;
      border: none;
      color: white;
      padding: 16px 32px;
      text-decoration: none;
      margin: 4px 2px;
      cursor: pointer;
    }
</style>

</head>


<!-- page wrapper -->
<body>

    <div class="boxed_wrapper">


        <!-- preloader -->
        <div class="loader-wrap">
            <div class="preloader">
                <div class="preloader-close">Preloader Close</div>
                <div id="handle-preloader" class="handle-preloader">
                    <div class="animation-preloader">
                        <div class="spinner"></div>
                        <div class="txt-loading">
                            <span data-text-preloader="n" class="letters-loading">
                                N
                            </span>
                            <span data-text-preloader="b" class="letters-loading">
                                B
                            </span>
                            <span data-text-preloader="a" class="letters-loading">
                                A
                            </span>
                        </div>
                    </div>  
                </div>
            </div>
        </div>
        <!-- preloader end -->

        <!-- main header -->
        <header class="main-header style-one">
            <!-- header-top -->
            <div class="header-top">
                <div class="auto-container">
                    <div class="top-inner clearfix">
                        <div class="left-column pull-left clearfix">
                            <div class="weathre-box"><p style="color: white;">For live updates</p></div>
                            <ul class="links-box clearfix">
                                <li><a href="https://www.nba.com/" style="color: red;">NBA</a></li>
                                <li><a href="https://www.espn.com/nba/" style="color: red;">ESPN</a></li>
                                <li><a href="https://www.cbssports.com/nba/" style="color: red;">CBS</a></li>
                            </ul>
                        </div>
                        <div class="right-column pull-right clearfix">
                            <p style="color: white;">
                                Check out the <a href="https://www.balldontlie.io/#introduction" style="color: red;">BallDon'tLie API</a>
                            </p>
                        </div>
                    </div>
                </div>
            </div>

            <!-- header-lower -->
            <div class="header-lower">
                <div class="auto-container">
                    <div class="outer-box clearfix">
                        <div class="logo-box pull-left">
                            <figure class="logo"><img src="/assets/images/Ball-dont-lie.png" alt="" height="55" width="85" style="padding: 0; margin: -10px;"></a></figure>
                        </div>
                        <div class="menu-area clearfix pull-right">
                            <!--Mobile Navigation Toggler-->
                            <div class="mobile-nav-toggler">
                                <i class="icon-bar"></i>
                                <i class="icon-bar"></i>
                                <i class="icon-bar"></i>
                            </div>
                            <nav class="main-menu navbar-expand-md navbar-light">
                                <div class="collapse navbar-collapse show clearfix" id="navbarSupportedContent">
                                    <ul class="navigation clearfix">
                                        <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                                        <li><a asp-area="" asp-controller="PlayerRoots" asp-action="Index">Players</a></li> 
                                        <li><a asp-area="" asp-controller="TeamRoots" asp-action="Index">Teams</a></li>
                                        <li><a asp-area="" asp-controller="ComparisonPage" asp-action="Index" style="color: red;">Stat Comparisons</a></li>
                                        <li><a asp-area="" asp-controller="ReportsPage" asp-action="Index">Reports</a></li>
                                        @if (User.IsInRole(SD.Admin))
                                        {
                                            <li><a asp-area="" asp-controller="UserRoles" asp-action="Index">Manage Users</a></li> 
                                        }
                                    </ul>
                                </div>
                            </nav>
                            <div class="menu-right-content clearfix">
                                <div class="collapse navbar-collapse show clearfix" id="navbarSupportedContent">
                                    <partial name="_LoginPartial" />
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- main-header end -->

        <!-- Mobile Menu  -->
        <div class="mobile-menu">
            <div class="menu-backdrop"></div>
            <div class="close-btn"><i class="fas fa-times"></i></div>
            
            <nav class="menu-box">
                <div class="nav-logo"><a href="index.html"><img src="/assets/images/logo-2.png" alt="" title=""></a></div>
                <div class="menu-outer"><!--Here Menu Will Come Automatically Via Javascript / Same Menu as in Header--></div>
            </nav>
        </div><!-- End Mobile Menu -->

        <section class="page-title" style="background-image: url(/assets/images/background/compareBanner.jpeg);">
            <div class="auto-container">
                <div class="content-box">
                    <div class="title centred">
                        <h1>Compare Player Stats</h1>
                    </div>
                    <ul class="bread-crumb clearfix">
                        <li><a asp-area="" asp-class="nav-link" asp-controller="Home" asp-action="Index" style="color: red;">BallDon'tLie</a></li>
                        <li>Compare</li>
                    </ul>
                </div>
            </div>
        </section>

        <section class="site-content" style="margin: 20px;">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-12">
                        @RenderBody()
                        @if (IsSectionDefined("scripts"))
                        {
                            RenderSection("scripts");
                        }
                    </div>
                </div>
            </div>
        </section>

         <!-- main-footer -->
        <footer class="main-footer">
            <div class="footer-top pt-50">
                <div class="auto-container">
                    <div class="top-inner">
                        <div class="row clearfix">
                            <div class="col-lg-3 col-md-6 col-sm-12 logo-column">
                                <figure class="footer-logo"><a href="index.html"><img src="/assets/images/nba-logo-transparent.png" alt=""></a></figure>
                            </div>
                            <div class="col-lg-5 col-md-6 col-sm-12 text-column">
                                <div class="text">
                                    <h3>Thank you for visiting BallDon'tLie</h3>
                                    <P>We hope that this site brings you closer to the game!</P>
                                </div>
                            </div>
                            <div class="col-lg-4 col-md-12 col-sm-12 form-column">
                                <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index" style="color: red;">Return to Home Page</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            
            </div>
            <div class="footer-bottom">
                <div class="auto-container">
                    <div class="bottom-inner clearfix">
                        <div class="copyright pull-left">
                            <p>&copy; BallDon'tLie</p>
                        </div>
                        <ul class="footer-nav clearfix pull-right">
                            To contact us with questions/suggestions, email us at admin@balldontlie.com
                        </ul>
                    </div>
                </div>
            </div>
        </footer>
        <!-- main-footer end -->



        <!--Scroll to top-->
        <button class="scroll-top scroll-to-target" data-target="html">
            <span class="fas fa-angle-up"></span>
        </button>
    </div>


    

</body><!-- End of .page_wrapper -->
</html>